# Generated by Django 4.2.7 on 2024-01-15 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_2',
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
