# Generated by Django 4.2.7 on 2024-01-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_title_2_alter_product_description_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
