# Generated by Django 4.2.7 on 2024-01-10 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
    ]
