# Generated by Django 4.2.7 on 2024-01-10 18:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_slide_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='data',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='data',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='data',
            name='products',
        ),
        migrations.AddField(
            model_name='data',
            name='title_1',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст №1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='title_2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст №2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='title_3',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст №3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='title_4',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст №4'),
            preserve_default=False,
        ),
    ]
