# Generated by Django 4.2.7 on 2024-01-12 16:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_data_clients_remove_data_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
