# Generated by Django 4.2.7 on 2024-01-12 16:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_about_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
    ]
